# Generated by Django 4.1.2 on 2023-01-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstats',
            name='days_count',
            field=models.IntegerField(default=0),
        ),
    ]
