# Generated by Django 4.1.2 on 2023-01-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productstats_days_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstats',
            old_name='days_count',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='productstats',
            name='average_price',
        ),
        migrations.AddField(
            model_name='productstats',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
